#! /usr/bin/python3
import os
import sys
import warnings
# input_param=sys.argv[1]
if(len(sys.argv)==2):   
    if(sys.argv[1] not  in ["on","off","ON","OFF"]):
        warnings.warn("Wrong paramter please specify 'on' or 'off' !")
    elif(sys.argv[1] in ["on","off","ON","OFF"]):
        if(sys.argv[1] in ["on","ON"]):
            os.system("nmcli r wifi on && nmcli device wifi  hotspot ifname wlp2s0 ssid manimohan_hotspot password manimohan_hotspot@123")
        elif(sys.argv[1] in ["off","OFF"]):
            os.system("nmcli r wifi off && nmcli r wifi on")
elif(len(sys.argv)!=2):
    warnings.warn("Please pass 'on' or 'off' as parameter")

